### ISSUE TITLE
add logos from sponsor

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/BaselHack.github.io#11]
gross: SuperMario und Zelda
mittel: Pacman
klein: Tetris

**Comment by teddybeaker** [comment]
@jjerlich , @JJatsch, @culmat , @michelpfirter: ich fände es wichtig, dass wir die Sponsoren-Logos auf der Webseite platzieren, sobald die jeweiligen Zahlungen eingegangen sind. Ich würde was analog zu www.frontendconf.ch (ganz unten auf der Seite) machen. Oder hat sich jemand von euch schon was anderes dazu überlegt?

**Comment by teddybeaker** [comment]
Logo from Basler is currently on test.baselhack.ch

**Comment by teddybeaker** [comment]
Draft looks like this:
![draft_sponsoring](https://user-images.githubusercontent.com/2244342/29497506-21bb4e72-85e9-11e7-8967-24f13429c02c.png)
will upload to test as soon as test is merged to master. (will remove blue placeholders beforehand of course 😄 )

**Comment by michelpfirter** [comment]
looks good to me, but on test it is just the Baloise logo - do not see any others

**Comment by teddybeaker** [comment]
@michelpfirter : didn't upload to test yet. But logos will only be enabled once we receive the money. So it will probably be Baloise-Only anyway at first 😄

**Comment by teddybeaker** [comment]
is now on test.baselhack.ch (with only Baloise active but other sponsors prepared).

**Comment by teddybeaker** [comment]
fix on spenden-pages

**Comment by teddybeaker** [comment]
is productive now

**Comment by jjerlich** [comment]
Checked the website right now - can see only Basler Logo, no other logos, check with Firefox and Google Chrome

**Comment by teddybeaker** [comment]
@jjerlich: thanks for checking. I didn't make the adobe-logo and bluesky-logo visible until yesterday evening (after you checked). the logo of fhnw will follow as soon as their payment arrives.
