### ISSUE TITLE
Inhaltsfokus

### ISSUE THREAD

**Issue by culmat** [BaselHack/BaselHack.github.io#2]
Mehr Fokus auf den Inhalt, also kleinere Gifs oder mehr Pause zwischen den Animationssequenzen ... oder beides :-)

**Comment by teddybeaker** [comment]
-> assign to Michel
assign to Rolf if not solveable

**Comment by michelpfirter** [comment]
6s delays introduced in animations ... on test.baselhack.ch ... have a look and please feedback
