### ISSUE TITLE
Texte übersetzen auf English

### ISSUE THREAD

**Issue by culmat** [BaselHack/BaselHack.github.io#3]
Siehe https://github.com/BaselHack/BaselHack.github.io/blob/master/index.en.html

**Comment by teddybeaker** [comment]
-> to Marina

**Comment by culmat** [comment]
dominik.strobel@ict-scouts.ch kann eventuel helfen. ( webilea event)

**Comment by mabrimo** [comment]
[Website Translation EN.docx](https://github.com/BaselHack/BaselHack.github.io/files/1169788/Website.Translation.EN.docx)

Translation is checked and ready to be integrated in Website
@culmat kannst du das vielleicht übernehmen? ich habe es versucht, aber da ich die codes um den eigentlichen text nicht verstehe, habe ich es am ende nicht gespeichert ;-)

**Comment by teddybeaker** [comment]
werde es mir heute Abend anschauen

**Comment by teddybeaker** [comment]
Die Texte sind übernommen (siehe https://baselhack.ch/index.en.html). z.T. habe ich noch selber ergänzt, was im Translation-File nicht drin war.
@mabrimo: kannst du bitte auch nochmal drüberschauen?
Werde als nächstes noch den Switch (de/en) einbauen

**Comment by mabrimo** [comment]
Alles klar, mache ich morgen Nachmittag gerne ☺

Von: Stefani Gerber [mailto:notifications@github.com]
Gesendet: Dienstag, 25. Juli 2017 17:31
An: BaselHack/BaselHack.github.io <BaselHack.github.io@noreply.github.com>
Cc: Morawietz Marina <marina.morawietz@fhnw.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [BaselHack/BaselHack.github.io] Texte übersetzen auf English (#3)


Die Texte sind übernommen (siehe https://baselhack.ch/index.en.html). z.T. habe ich noch selber ergänzt, was im Translation-File nicht drin war.
@mabrimo<https://github.com/mabrimo>: kannst du bitte auch nochmal drüberschauen? Falls ok kannst du das Ticket schliessen.
Werde als nächstes noch den Switch (de/en) einbauen (#4<https://github.com/BaselHack/BaselHack.github.io/issues/4>)

**Comment by teddybeaker** [comment]
ok from Nely (on Slack)
